### ISSUE TITLE
does not support ES6 enhanced object literals

### ISSUE THREAD

**Issue by rockie** [fengmk2/istanbul#3]
When I am using the enhanced object literals syntax like [Node ES6](https://github.com/lukehoban/es6features#enhanced-object-literals) in a file, it will report "Unexpected identifier" for the shorthand syntax and 'Duplicate data property in object literal not allowed in strict mode' for the computed dynamic property and finally fail to instrument that file.  (with "istanbul-harmony": "0.3.16")

**Comment by fengmk2** [comment]
please use istanbul>=0.4.0 instead, this istanbul-harmony module was deprecated.
